config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :goal_kvms
  resources :measurements
  resources :experiments
  resources :goals
  resources :kvms
  resources :kvas
  resources :organizations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :registrations, only: [ :new, :create ]
  resources :sessions, only: [ :new, :create, :destroy ]
  resources :passwords, param: :token

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "organizations#index"
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :goal
  has_many :measurements, dependent: :nullify

  # To define statuses
  enum :status, {
    planned: "Planned",
    running: "Running",
    completed: "Completed",
    cancelled: "Cancelled"
  }
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: %i[ show edit update destroy ]

  # GET /experiments or /experiments.json
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1 or /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments or /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: "Experiment was successfully created." }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1 or /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: "Experiment was successfully updated." }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1 or /experiments/1.json
  def destroy
    @experiment.destroy!

    respond_to do |format|
      format.html { redirect_to experiments_path, status: :see_other, notice: "Experiment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def experiment_params
      params.expect(experiment: [ :name, :hypothesis, :actions_taken, :start_date, :end_date, :status, :inspection_summary, :adaptation_summary, :goal_id ])
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_experiment.html.erb
<div id="<%= dom_id experiment %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= experiment.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Hypothesis:</strong>
    <%= experiment.hypothesis %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Actions taken:</strong>
    <%= experiment.actions_taken %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= experiment.start_date %>
  </div>
  <div>
    <strong class="block font-medium mb-1">End date:</strong>
    <%= experiment.end_date %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Status:</strong>
    <%= experiment.status %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Inspection summary:</strong>
    <%= experiment.inspection_summary %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Adaptation summary:</strong>
    <%= experiment.adaptation_summary %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Goal:</strong>
    <%= experiment.goal_id %>
  </div>
</div>

app/views/experiments/_form.html.erb
<%= form_with(model: experiment, class: "contents") do |form| %>
  <% if experiment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% experiment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:name].none?, "border-red-400 focus:outline-red-600": experiment.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :hypothesis %>
    <%= form.textarea :hypothesis, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:hypothesis].none?, "border-red-400 focus:outline-red-600": experiment.errors[:hypothesis].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :actions_taken %>
    <%= form.textarea :actions_taken, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:actions_taken].none?, "border-red-400 focus:outline-red-600": experiment.errors[:actions_taken].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.datetime_field :start_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:start_date].none?, "border-red-400 focus:outline-red-600": experiment.errors[:start_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.datetime_field :end_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:end_date].none?, "border-red-400 focus:outline-red-600": experiment.errors[:end_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.text_field :status, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:status].none?, "border-red-400 focus:outline-red-600": experiment.errors[:status].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :inspection_summary %>
    <%= form.textarea :inspection_summary, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:inspection_summary].none?, "border-red-400 focus:outline-red-600": experiment.errors[:inspection_summary].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :adaptation_summary %>
    <%= form.textarea :adaptation_summary, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:adaptation_summary].none?, "border-red-400 focus:outline-red-600": experiment.errors[:adaptation_summary].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :goal_id %>
    <%= form.text_field :goal_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": experiment.errors[:goal_id].none?, "border-red-400 focus:outline-red-600": experiment.errors[:goal_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<% content_for :title, "Editing experiment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing experiment</h1>

  <%= render "form", experiment: @experiment %>

  <%= link_to "Show this experiment", @experiment, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to experiments", experiments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/experiments/index.html.erb
<% content_for :title, "Experiments" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Experiments</h1>
    <%= link_to "New experiment", new_experiment_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="experiments" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @experiments.any? %>
      <% @experiments.each do |experiment| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render experiment %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", experiment, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_experiment_path(experiment), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", experiment, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No experiments found.</p>
    <% end %>
  </div>
</div>

app/views/experiments/new.html.erb
<% content_for :title, "New experiment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New experiment</h1>

  <%= render "form", experiment: @experiment %>

  <%= link_to "Back to experiments", experiments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/experiments/show.html.erb
<% content_for :title, "Showing experiment" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing experiment</h1>

  <%= render @experiment %>

  <%= link_to "Edit this experiment", edit_experiment_path(@experiment), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to experiments", experiments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this experiment", @experiment, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>